sudo: required
services:
  - docker

before_install:
  - docker build -t bitch0mp/docker-react -f Dockerfile.dev .

script:
  - docker run bitch0mp/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Udemy"
  env: "udemy-env"
  bucket_name: "elasticbeanstalk-us-east-1-342939767414"
  bucket_path: "Udemy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
