FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# ADDED FOLLOWING DUE TO ERROR; NOT PART OF TUTORIAL
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . . 

CMD ["npm", "run", "start"]